#!/usr/bin/env python3
"""Turns the CRT TV mesh from Roadside / Farlands Views (src/render/TvMeshData.hpp)
into crt.js, which tv.js imports. The model is PSX CRT TV by Tomitos (CC BY 4.0),
see CREDITS.md.

The source has its front facing -y, up along +z. Here the front faces -z
(into the kitchen) and up is +y: (x, y, z) becomes (-x, z, y), a plain
rotation, so nothing gets mirrored or turned inside out.

    python3 tools/export-crt.py ../roadside/src/render/TvMeshData.hpp
"""
import re, sys, os

src = open(sys.argv[1]).read()

def floats(block):
    return [float(v) for v in re.findall(r'-?\d+\.?\d*(?:e[-+]?\d+)?(?=f)', block)]

def block(name):
    m = re.search(name + r'[^=]*=\s*\{(.*?)\n\};', src, re.S)
    return m.group(1)

verts = floats(block('kRtTvVertices'))
assert len(verts) == 115 * 6
idx = [int(v) for v in re.findall(r'\d+', block('kRtTvIndices'))]
assert len(idx) == 186
scr = floats(block('kRtTvScreenVertices'))
assert len(scr) == 20

def r(v): return round(v, 5)
pos, nor = [], []
for i in range(0, len(verts), 6):
    x, y, z, nx, ny, nz = verts[i:i + 6]
    pos += [r(-x), r(z), r(y)]
    nor += [r(-nx), r(nz), r(ny)]
# make every triangle wind the way its vertex normals point (the source
# winding is for a mirrored frame, so some triangles come out backwards)
def sub(a, b): return [a[i] - b[i] for i in range(3)]
def cross(a, b): return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]]
fixed = []
for t in range(0, len(idx), 3):
    a, b, c = idx[t:t + 3]
    P = lambda i: pos[i * 3:i * 3 + 3]
    N = lambda i: nor[i * 3:i * 3 + 3]
    g = cross(sub(P(b), P(a)), sub(P(c), P(a)))
    if sum(g[k] * N(a)[k] for k in range(3)) < 0:
        b, c = c, b
    fixed += [a, b, c]
idx = fixed
sp, suv = [], []
for i in range(0, 20, 5):
    x, y, z, u, v = scr[i:i + 5]
    sp += [r(-x), r(z), r(y)]
    suv += [u, 1 - v]

out = os.path.join(os.path.dirname(__file__), '..', 'crt.js')
with open(out, 'w') as f:
    f.write('// Generated by tools/export-crt.py: PSX CRT TV by Tomitos (CC BY 4.0), see CREDITS.md.\n')
    f.write('// Units are the model\'s own (0.6 wide); front faces -z, up is +y.\n')
    for k, v in [('POSITIONS', pos), ('NORMALS', nor), ('INDICES', idx),
                 ('SCREEN_POSITIONS', sp), ('SCREEN_UVS', suv), ('SCREEN_INDICES', [0, 1, 2, 0, 2, 3])]:
        f.write('export const %s = %s;\n' % (k, v))
print('wrote', out)
